# Generated by Django 4.0.4 on 2022-09-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='PhotoFileName',
            new_name='Photo',
        ),
    ]
