# Generated by Django 4.0.4 on 2022-09-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_rename_department_departments_employee_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
