# Generated by Django 4.0.4 on 2022-09-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_employee_email_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Email',
            field=models.EmailField(default='sample@gmail.com', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='Phone',
            field=models.CharField(default='07036872481', max_length=20),
            preserve_default=False,
        ),
    ]
