# Generated by Django 4.0.4 on 2022-10-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_alter_employee_email_alter_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Salary',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
